% Automatically generated by Team M's spritesheet compiler.
% 25 sprites compiled on 2025-11-22.
classdef(Enumeration) Sprites < uint32
    enumeration
        CHECKBOX_FALSE (1)
        CHECKBOX_TRUE (2)
        EMPTY (3)
        GEAR (4)
        GRASS0 (5)
        MENU (6)
        MENU_E (7)
        MENU_FOC_E (8)
        MENU_FOC_N (9)
        MENU_FOC_NE (10)
        MENU_FOC_NW (11)
        MENU_FOC_S (12)
        MENU_FOC_SE (13)
        MENU_FOC_SW (14)
        MENU_FOC_W (15)
        MENU_N (16)
        MENU_NE (17)
        MENU_NW (18)
        MENU_S (19)
        MENU_SE (20)
        MENU_SW (21)
        MENU_W (22)
        MISSING (23)
        ROAD (24)
        TILEBROWNSMALL (25)
    end
end
