% Automatically generated by Team M's map generator.
% 27 collider types registered on 2025-11-25.
classdef(Enumeration) Collider < uint32
    enumeration
        NORTH (32767)
        KNOWLTON_HALL (32766)
        ENARSON_CLASSROOM_BLDG (32765)
        MCCRACKEN_POWER_PLANT (32764)
        DREESE_LABS (32763)
        BAKER_SYSTEMS (32762)
        HITCHCOCK_HALL (32761)
        BOLZ_HALL (32760)
        CALDWELL_LABS (32759)
        JOURNALISM_BLDG (32758)
        COCKINS_HALL (32757)
        MATHEMATICS_BLDG (32756)
        MATHEMATICS_TOWER (32755)
        SCOTT_LABS (32754)
        PHYSICS_RESEARCH_BLDG (32753)
        X_209_W_18TH (32752)
        X_18TH_AVE_LIBRARY (32751)
        SMITH_LABS (32750)
        CBEC (32749)
        FONTANA_LAB (32748)
        MCPHERSON_LAB (32747)
        CELESTE_LAB (32746)
        STILLMAN_HALL (32745)
        OXLEYS (32744)
        WALL (8339327)
        BARRIER (16777215)
        PATH (8355711)
        EMPTY (0)
   end
end
