% Registry of each world and its associated data files.
% I could have made maps/generate.py make this automatically, but there are few
%   enough maps that I don't think it would be worth it
% You may have to use maps/generate.py to build the referenced CSV files.
classdef(Enumeration) WorldKind
    properties(Constant)
        SPRITES = dictionary( ...
            world.WorldKind.ENGINEERING_CORE, ...
                'maps/engineering_core.sprites.csv' ...
        );
        COLLIDERS = dictionary( ...
            world.WorldKind.ENGINEERING_CORE, ...
                'maps/engineering_core_colliders.colliders.csv' ...
        );
    end
    enumeration
        ENGINEERING_CORE
    end
end