#!/usr/bin/python3
# vim: sw=4 sts=4 ts=4 et
from datetime import datetime
from os import path
from sys import argv

from PIL import Image

from colormap import spritemap, collidermap, colliders

# either 'c' (colliders) or 's' (sprites)
mode = ""

try:
    if not argv[1].endswith(".png"):
        raise ValueError("File improper")
    if "colliders".startswith(argv[2]) or "sprites".startswith(argv[2]):
        mode = argv[2][0]
    else:
        raise ValueError("Unknown compile mode " + argv[2])
except:
    print("usage:", __file__, "<file.png> colliders|sprites")
    exit()


script_dir = path.dirname(__file__);
world_map_path = path.join(
    path.dirname(path.realpath(script_dir)),
    #script_dir,
    "%s.%s.csv" % (argv[1][:-4], 'sprites' if mode == "s" else 'colliders')
)

# Mapping function from pixel RGB to id
mapc = spritemap if mode == "s" else collidermap

im = Image.open(argv[1])
w, h = im.size

with open(world_map_path, "w") as wm:#, open(collider_map_path, "w")
    for y in range(h):
        row = []

        for x in range(w):
            r, g, b = im.getpixel((x, y))
            rgb = (r << 16) + (g << 8) + b
            
            row.append("%d" % mapc(rgb))

        print(",".join(row), file=wm)
    print(
        "-- Mapped %d pixels into %s" % (
            im.size[0] * im.size[1],
            world_map_path
        )
    )

if mode == "c":
    collider_id_map_path = path.join(
        path.dirname(path.realpath(script_dir)),
        "+world/Collider.m"
    )

    with open(collider_id_map_path, "w") as cidm:
        cidm.writelines([
                "% Automatically generated by Team M's map generator.\n",
                "%% %d collider types registered on %s.\n" \
                    % (
                        len(colliders),
                        datetime.now().strftime("%Y-%m-%d")
                    ),
                "classdef(Enumeration) Collider < uint32\n",
                "    enumeration\n"
        ])

        for (rgbid, name) in colliders.items():
            print(
                "        %s (%d)" % (name, rgbid),
                file=cidm
            )

        # static entry for the un-collider
        print("        EMPTY (0)", file=cidm)

        cidm.writelines([
                "   end\n",
                "end\n"
        ])

    print("-- Generated %d entries in %s" % (len(colliders), collider_id_map_path));
