#!/usr/bin/python3
from datetime import datetime
from glob import glob
import os

from PIL import Image

SPRITE_W = 16
SPRITE_H = 16
MAX_W_SPRITES = 16

xpos = lambda i: ((SPRITE_W + 1) * (i % MAX_W_SPRITES))
ypos = lambda i: ((SPRITE_H + 1) * (i // MAX_W_SPRITES))

script_dir = os.path.dirname(__file__);

files = glob(os.path.join(script_dir, "*.png"))
files = sorted([fi for fi in files if not fi.endswith("sheet.png")])
num_sprites = len(files)

if not num_sprites:
    print("No sprites. Script should be in the same dir as the source .pngs.")
    exit(1)

im = Image.new(
    "RGBA",
    (
        min(
          (SPRITE_W + 1) * num_sprites, 
          (SPRITE_W + 1) * MAX_W_SPRITES
        ) - 1,
        (num_sprites // MAX_W_SPRITES + 1) * (SPRITE_H + 1) - 1
    )
)

# fill the sheet with green - becomes borders
# can remove this line
im.paste( (0, 255, 0), (0, 0, im.size[0], im.size[1]) )

# Templates for parts of Sprites.m
constfile_header = [
        "% Automatically generated by Team M's spritesheet compiler.\n",
        "%% %d sprites compiled on %s.\n" \
            % (num_sprites, datetime.now().strftime("%Y-%m-%d")),
        "classdef(Enumeration) Sprites < uint32\n",
        "    enumeration\n"
]

constfile_entry_tpl = "        %s (%d)"

constfile_footer = [
        "    end\n",
        "end\n"
]

constsfile_path = os.path.join(
    os.path.dirname(os.path.realpath(script_dir)), 
    "+game/Sprites.m"
)

# Templates for map generator source maps

worldgen_sourcemap_header = [
        "# Automatically generated by Team M's spritesheet compiler.\n",
        "# %d sprites compiled on %s.\n" \
            % (num_sprites, datetime.now().strftime("%Y-%m-%d"))
]

worldgen_sourcemap_entry_tpl = "%s = %d"

worldgen_sourcemap_path = os.path.join(
    os.path.dirname(os.path.realpath(script_dir)),
    "maps/spritemap.py"
)

with open(constsfile_path, "w") as constsfile, open(
        worldgen_sourcemap_path, "w"
) as wgsm:
    constsfile.writelines(constfile_header)
    wgsm.writelines(worldgen_sourcemap_header)

    for (i, file) in enumerate(files):
        # insert the sprite at the correct offset
        sprite = Image.open(file)
        im.paste(sprite, (xpos(i), ypos(i)))

        # add the sprite to the index file
        print(
            constfile_entry_tpl \
                % (os.path.basename(file).split(".")[0].upper(), i + 1),
            file=constsfile
        )
        # add sprite to mapgen sourcemap file
        print(
            worldgen_sourcemap_entry_tpl \
                % (os.path.basename(file).split(".")[0].upper(), i + 1),
            file=wgsm
        )

    constsfile.writelines(constfile_footer)

# default sprite
sprite_missing = Image.open(os.path.join(script_dir, "missing.png"))

# fill the rest of the sheet with default sprite
for i in range(
        num_sprites, 
        (num_sprites // MAX_W_SPRITES + 1) * MAX_W_SPRITES 
):
    im.paste(sprite_missing, (xpos(i), ypos(i)))

sheet_path = os.path.join(script_dir, "sheet.png")
im.save(sheet_path)
print("-- Compiled %d sprites into %s" % (num_sprites, sheet_path))
