classdef Text < spruiten.Widget
    properties(Constant)
        GLYPHS = dictionary( ...
            'A',    game.Sprites.GLYPH_A, ...
            'B',    game.Sprites.GLYPH_B, ...
            'C',    game.Sprites.GLYPH_C, ...
            'D',    game.Sprites.GLYPH_D, ...
            'E',    game.Sprites.GLYPH_E, ...
            'F',    game.Sprites.GLYPH_F, ...
            'G',    game.Sprites.GLYPH_G, ...
            'H',    game.Sprites.GLYPH_H, ...
            'I',    game.Sprites.GLYPH_I, ...
            'J',    game.Sprites.GLYPH_J, ...
            'K',    game.Sprites.GLYPH_K, ...
            'L',    game.Sprites.GLYPH_L, ...
            'M',    game.Sprites.GLYPH_M, ...
            'N',    game.Sprites.GLYPH_N, ...
            'O',    game.Sprites.GLYPH_O, ...
            'P',    game.Sprites.GLYPH_P, ...
            'Q',    game.Sprites.GLYPH_Q, ...
            'R',    game.Sprites.GLYPH_R, ...
            'S',    game.Sprites.GLYPH_S, ...
            'T',    game.Sprites.GLYPH_T, ...
            'U',    game.Sprites.GLYPH_U, ...
            'V',    game.Sprites.GLYPH_V, ...
            'W',    game.Sprites.GLYPH_W, ...
            'X',    game.Sprites.GLYPH_X, ...
            'Y',    game.Sprites.GLYPH_Y, ...
            'Z',    game.Sprites.GLYPH_Z, ...
            '0',    game.Sprites.GLYPH_0, ...
            '1',    game.Sprites.GLYPH_1, ...
            '2',    game.Sprites.GLYPH_2, ...
            '3',    game.Sprites.GLYPH_3, ...
            '4',    game.Sprites.GLYPH_4, ...
            '5',    game.Sprites.GLYPH_5, ...
            '6',    game.Sprites.GLYPH_6, ...
            '7',    game.Sprites.GLYPH_7, ...
            '8',    game.Sprites.GLYPH_8, ...
            '9',    game.Sprites.GLYPH_9, ...
            '&',    game.Sprites.GLYPH_AMPERSAND, ...
            '!',    game.Sprites.GLYPH_EXCLAMATION_MARK, ...
            '.',    game.Sprites.GLYPH_POINT, ...
            ',',    game.Sprites.GLYPH_COMMA, ...
            ':',    game.Sprites.GLYPH_COLON, ...
            ' ',    game.Sprites.EMPTY ...
        );

        GLYPHS_WHITE = dictionary( ...
            'A',    game.Sprites.GLYPH_A_WHITE, ...
            'B',    game.Sprites.GLYPH_B_WHITE, ...
            'C',    game.Sprites.GLYPH_C_WHITE, ...
            'D',    game.Sprites.GLYPH_D_WHITE, ...
            'E',    game.Sprites.GLYPH_E_WHITE, ...
            'F',    game.Sprites.GLYPH_F_WHITE, ...
            'G',    game.Sprites.GLYPH_G_WHITE, ...
            'H',    game.Sprites.GLYPH_H_WHITE, ...
            'I',    game.Sprites.GLYPH_I_WHITE, ...
            'J',    game.Sprites.GLYPH_J_WHITE, ...
            'K',    game.Sprites.GLYPH_K_WHITE, ...
            'L',    game.Sprites.GLYPH_L_WHITE, ...
            'M',    game.Sprites.GLYPH_M_WHITE, ...
            'N',    game.Sprites.GLYPH_N_WHITE, ...
            'O',    game.Sprites.GLYPH_O_WHITE, ...
            'P',    game.Sprites.GLYPH_P_WHITE, ...
            'Q',    game.Sprites.GLYPH_Q_WHITE, ...
            'R',    game.Sprites.GLYPH_R_WHITE, ...
            'S',    game.Sprites.GLYPH_S_WHITE, ...
            'T',    game.Sprites.GLYPH_T_WHITE, ...
            'U',    game.Sprites.GLYPH_U_WHITE, ...
            'V',    game.Sprites.GLYPH_V_WHITE, ...
            'W',    game.Sprites.GLYPH_W_WHITE, ...
            'X',    game.Sprites.GLYPH_X_WHITE, ...
            'Y',    game.Sprites.GLYPH_Y_WHITE, ...
            'Z',    game.Sprites.GLYPH_Z_WHITE, ...
            '0',    game.Sprites.GLYPH_0_WHITE, ...
            '1',    game.Sprites.GLYPH_1_WHITE, ...
            '2',    game.Sprites.GLYPH_2_WHITE, ...
            '3',    game.Sprites.GLYPH_3_WHITE, ...
            '4',    game.Sprites.GLYPH_4_WHITE, ...
            '5',    game.Sprites.GLYPH_5_WHITE, ...
            '6',    game.Sprites.GLYPH_6_WHITE, ...
            '7',    game.Sprites.GLYPH_7_WHITE, ...
            '8',    game.Sprites.GLYPH_8_WHITE, ...
            '9',    game.Sprites.GLYPH_9_WHITE, ...
            '&',    game.Sprites.GLYPH_AMPERSAND_WHITE, ...
            '!',    game.Sprites.GLYPH_EXCLAMATION_MARK_WHITE, ...
            '.',    game.Sprites.GLYPH_POINT_WHITE, ...
            ',',    game.Sprites.GLYPH_COMMA_WHITE, ...
            ':',    game.Sprites.GLYPH_COLON_WHITE, ...
            ' ',    game.Sprites.EMPTY ...
        );
    end
    properties
        content (:, :) char = '';
        white (1, 1) logical = false;

        % Defined in Widget. See spruiten.Wdiget for explanation
        %pos = [1, 1]; % validation on inherited properties is broken R2024b
        %dims = [1, 1]; % "
    end

    methods

        % Use single quotes when passing `content`
        function self = Text(pos)
            arguments
                pos (1, 2) {mustBeInteger, mustBePositive}
            end

            self.pos = pos;
        end

        function click(self, btn) %#ok<INUSD> required by Widget class
        end
        
        function sprites = show(self)
            arguments   
                self (1, 1) %Text
            end

            % needs fix from MathWorks - currently no way to construct a
            %   dictionary with char keys, so we must convert to strings

            sprites = zeros(self.dims);

            for row = 1:self.dims(1) % lines/rows
                for col = 1:self.dims(2) % chars/cols
                    if (self.white)
                        sprites(row, col) = spruiten.widgets.Text.GLYPHS_WHITE(string(self.content(row, col)));
                    else
                        sprites(row, col) = spruiten.widgets.Text.GLYPHS(string(self.content(row, col)));
                    end
                end
            end
        end

        function res = encloses(self, point)
            res = all(self.pos <= point) && all(point < (self.pos + self.dims));
        end

        function self = set_content(self, content)
            arguments
                self (1, 1) %spruiten.Widgets.Text
                content (:, :) char
            end

            content = upper(char(content));

            self.content = content;
            self.dims = size(content);
        end

        function self = set_white(self, white)
            arguments
                self (1, 1) %spruiten.Widgets.Text
                white (1, 1) logical
            end

            self.white = white;
        end
    end
end